visual_encoder:
  _target_: modules.VitPoseVisualEncoder
  id: usyd-community/vitpose-plus-small
  hidden_states_layer: -2

visual_adapter:
  _target_: modules.VitPoseVisualEncoder
  hidden_size: 384
  target_hidden_size: 1152
  num_heads: 6
  num_layers: 2
  num_extra_queries: 4

shared_encoder:
  _target_: modules.SignBertEncoder
  hidden_size: 1152
  num_attention_heads: 4
  num_layers: 12
  max_position_embeddings: 1024
  intermediate_size: 2304
