visual_encoder:
  _target_: modules.VitPoseVisualEncoder
  id: usyd-community/vitpose-plus-small
  hidden_states_layer: -2

visual_adapter:
  _target_: modules.VisualAdapter
  hidden_size: 384
  target_hidden_size: 768
  num_heads: 6
  num_layers: 2
  num_extra_queries: 4

bert_shared_encoder_id: dbmdz/bert-base-german-europeana-cased
