visual_encoder:
  _target_: modules.VitPoseVisualEncoder
  id: usyd-community/vitpose-plus-base
  hidden_states_layer: -2

visual_adapter:
  _target_: modules.TokenSampleAdapter
  hidden_size: 768
  num_heads: 6
  num_layers: 2
  num_extra_queries: 8

predictor_depth: 2
