visual_encoder:
  _target_: modules.VitPoseVisualEncoder
  id: usyd-community/vitpose-plus-base
  hidden_states_layer: -2

visual_adapter:
  _target_: modules.VisualAdapter
  hidden_size: 768
  target_hidden_size: 1024
  num_heads: 6
  num_layers: 2
  num_extra_queries: 8

bert_shared_encoder_id: google-bert/bert-large-uncased
num_query_token: 64

freezer:
  _target_: modules.FullFreezer

num_soft_prompt_token: 10
