defaults:
  - decoder: llama_cross_decoder
  - encoder: sign_bert_encoder
  - visual_backbone: timm_visual_encoder
  - loss: loss
  - engine: default
  - data: ph14t_keywords
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

max_epochs: 50
debug: True
devices: [0, 1]
