defaults:
  - modules: default
  - engine: default
  - data: ph14t_keywords
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

max_epochs: 100
debug: True
devices: [0, 1]

vtg_flag: True
vtg_weight: 1.0
vtg_random_replace_prob: 0.6 #To better
vtg_mask_replace_prob: 0.3
vtg_mask_ratio: 0.5

vtm_flag: True
vtm_mask_ratio: 0.40
vtm_weight: 1.0
vtm_random_replace_prob: 0.1
vtm_mask_replace_prob: 0.8

vtc_flag: True
vtc_weight: 1.0
vtc_queue_max_size: 2048

prompt_learning: False
inference_mode: False
