defaults:
  - modules: default
  - loss: loss
  - engine: default
  - data: ph14t_keywords
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

max_epochs: 100
debug: True
devices: [0, 1]

itc_flag: False
itc_weight: 1.0

mlm_flag: True
mlm_weight: 1.0

prompt_learning: False
