defaults:
  - modules: t5_text_pretrain
  - data: ph14t_text_only
  - engine: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
