defaults:
  - modules: default
  - engine: default
  - data: ph14t_keywords
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

max_epochs: 100
debug: True
devices: [0, 1]

vtg_flag: True
vtg_weight: 1.0

vtm_flag: True
vtm_mask_ratio: 0.40
vtm_weight: 1.0

vtc_flag: True
vtc_weight: 1.0

prompt_learning: False

inference_mode: False
