defaults:
  - base_train
  # - override data: ph14t_with_text_aug
  - override modules: vitpose_base_sampler
  # - override engine: cosine_anneal
  - _self_

debug: False
max_epochs: 65
devices: [2, 3, 4, 5, 6, 7]
precision: bf16-mixed

data:
  batch_size: 12
  batch_size_val_test: 4
  datamodule:
    num_workers: 6

engine:
  lr_scheduler:
    step_size: 25
  optimizer:
    lr: 1e-4

vtg_flag: True
vtg_weight: 1.0
vtg_mask_ratio: 0.0
vtg_random_replace_prob: 0.5
vtg_mask_replace_prob: 0.5

vtm_flag: True
vtm_mask_ratio: 0.8
vtm_weight: 1.0
vtm_random_replace_prob: 0.3
vtm_mask_replace_prob: 0.6

vtc_flag: True
vtc_weight: 1.0

prompt_learning: False
inference_mode: False

ph14t:
  extended_csv_dir: outputs/ph14t_text_augmented
