defaults:
  - base_train
  - _self_

debug: False
max_epochs: 100

engine:
  lr_scheduler:
    step_size: 50
  optmizer:
    lr: 1e-4

vtg_flag: True
vtg_weight: 1.0
vtg_mask_ratio: 0.40

vtm_flag: True
vtm_mask_ratio: 0.8
vtm_weight: 1.0

vtc_flag: False
vtc_weight: 1.0

prompt_learning: False

inference_mode: False
