defaults:
  - base_train
  - override modules: vitpose_base
  # - override data: ph14t_with_text_aug
  - _self_

debug: False
max_epochs: 400
devices: [0, 1]

data:
  batch_size: 4
  batch_size_val_test: 2
  datamodule:
    num_workers: 8

engine:
  lr_scheduler:
    step_size: 100
  optimizer:
    lr: 1e-4

vtg_flag: True
vtg_weight: 1.0
vtg_mask_ratio: 0.0
vtg_random_replace_prob: 0.5
vtg_mask_replace_prob: 0.5

vtm_flag: True
vtm_mask_ratio: 0.8
vtm_weight: 1.0
vtm_random_replace_prob: 0.3
vtm_mask_replace_prob: 0.6

vtc_flag: True
vtc_weight: 1.0

ph14t:
  extended_csv_dir: outputs/ph14t_text_augmented
