defaults:
  - base_train
  - _self_

debug: False
max_epochs: 400
devices: [0, 1]

data:
  batch_size: 2

engine:
  lr_scheduler:
    step_size: 50
  optimizer:
    lr: 1e-4

vtg_flag: False
vtg_weight: 1.0
vtg_mask_ratio: 0.0
vtg_random_replace_prob: 0.5
vtg_mask_replace_prob: 0.5

vtm_flag: False
vtm_mask_ratio: 0.8
vtm_weight: 1.0
vtm_random_replace_prob: 0.3
vtm_mask_replace_prob: 0.6

vtc_flag: False
vtc_weight: 1.0
vtc_queue_max_size: 4096

pl_flag: True
pl_weight: 1.0

inference_mode: False

pretrained_checkpoint: outputs/train/2025-06-01_04-11-15/thi7w9k5-epoch=66-val_generate_bleu=0.2953.ckpt
