defaults:
  - base_train
  - _self_

debug: False
max_epochs: 100

engine:
  lr_scheduler:
    step_size: 50
  optmizer:
    lr: 1e-2

data:
  batch_size: 2
  batch_size_val_test: 1

devices: [0, 1]

vtg_flag: False
vtg_weight: 1.0

vtm_flag: False
vtm_mask_ratio: 0.40
vtm_weight: 1.0

pl_flag: True
pl_weight: 1.0

pretrained_checkpoint: /root/projects/slt_set_llms/outputs/train/2025-05-15_21-28-48/epoch=epoch=72-wer=val_token_level_accu=0.00.ckpt
